dist: trusty
sudo: false

language: node_js
node_js:
  - '10'

env:
  global:
    - COVERALLS_PARALLEL=true

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - ./node_modules

install:
  - yarn

script:
  - yarn test -- --no-watch --no-progress --code-coverage --browsers=ChromeHeadlessCI

